# fly.toml app configuration file generated for nipple-game-frontend

app = 'nipple-game-frontend'
primary_region = 'fra'

[build]

[env]
  VITE_API_BASE_URL = 'https://backend-small-firefly-1588.fly.dev'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  interval = '15s'
  timeout = '2s'
  grace_period = '5s'
  method = 'GET'
  path = '/health'
  protocol = 'http'
  tls_skip_verify = false

[http_service.concurrency]
  type = 'connections'
  hard_limit = 25
  soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
